name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4', '8.0' ]
        allow-failure: [ false ]
        coverage: [ false ]
        composer-flags: [ '' ]
        include:
          - php-version: '7.3'
            coverage: true
          - php-version: '8.1'
            allow-failure: true
            composer-flags: '--ignore-platform-req php'

    steps:
      - uses: actions/checkout@v2

      - name: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: composer-validate
        run: composer validate

      - name: composer-cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: composer-install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-flags }}

      - name: php-cs-fixer
        continue-on-error: ${{ matrix.allow-failure }}
        env:
          PHP_CS_FIXER_IGNORE_ENV: ${{ matrix.allow-failure }}
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --config=.php_cs.dist

      - name: phpunit
        run: composer run-script phpunit

      - name: coverage
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build
