name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.1', '7.2', '7.3', '7.4' ]
        allow-failure: [ false ]
        composer-flags: [ '' ]
        include:
          - php-versions: '8.0'
            allow-failure: true
            omposer-flags: '--ignore-platform-req php'

    steps:
      - uses: actions/checkout@v2

      - name: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: composer-validate
        run: composer validate

      - name: composer-cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - name: composer-install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-flags }}

      - name: php-cs-fixer
        continue-on-error: ${{ matrix.allow-failure }}
        env:
          PHP_CS_FIXER_IGNORE_ENV: ${{ matrix.allow-failure }}
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --config=.php_cs.dist

      - name: phpunit
        run: vendor/bin/phpunit
