name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        coverage: [false]
        include:
          - php-versions: '7.2'
            coverage: true

    steps:
      - uses: actions/checkout@v2

      - name: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: composer-validate
        run: composer validate

      - name: composer-cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - name: composer-install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --config=.php_cs.dist

      - name: phpunit
        run: vendor/bin/phpunit --coverage-text --coverage-clover=build/coverage.xml

      - name: coverage-upload
        if: matrix.coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
